/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-05-01 02:45:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class request_005fform1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Html的form表单元素</title>\n");
      out.write("</head>\n");
      out.write("<fieldset style=\"width:500px;\">\n");
      out.write("\t<legend>Html的Form表单元素</legend>\n");
      out.write("\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RequestDemo3\" method=\"post\">\n");
      out.write("\t编&nbsp;&nbsp;号(文本框)：\n");
      out.write("\t\t<input type=\"text\" name=\"userid\" value=\"NO.\" size=\"2\" maxlength=\"2\"><br>\n");
      out.write("\t用户名(文本框)：\n");
      out.write("\t\t<input type=\"text\" name=\"username\" value=\"请输入用户名\"><br>\n");
      out.write("\t密&nbsp;&nbsp;码(密码框)：\n");
      out.write("\t<input type=\"password\" name=\"userpass\" value=\"请输入密码\"><br>\n");
      out.write("\t性&nbsp;&nbsp;别(单选框)：\n");
      out.write("\t<input type=\"radio\" name=\"sex\" value=\"男\" checked>男\n");
      out.write("\t<input type=\"radio\" name=\"sex\" value=\"女\">女<br>\n");
      out.write("\t部&nbsp;&nbsp;门(下拉框)：\n");
      out.write("\t<select name=\"dept\">\n");
      out.write("\t\t<option value=\"技术部\">技术部</option>\n");
      out.write("\t\t<option value=\"销售部\" selected>销售部</option>\n");
      out.write("\t\t<option value=\"财务部\">财务部</option>\n");
      out.write("\t</select><br>\n");
      out.write("\t兴&nbsp;&nbsp;趣(复选框)：\n");
      out.write("\t<input type=\"checkbox\" name=\"inst\" value=\"唱歌\">唱歌\t\n");
      out.write("\t<input type=\"checkbox\" name=\"inst\" value=\"游泳\">游泳\t\n");
      out.write("\t<input type=\"checkbox\" name=\"inst\" value=\"编程\">编程\n");
      out.write("\t<input type=\"checkbox\" name=\"inst\" value=\"跳舞\">跳舞\t\n");
      out.write("\t<input type=\"checkbox\" name=\"inst\" value=\"上网\">上网\t\n");
      out.write("\t<br>\n");
      out.write("\t说&nbsp;&nbsp;明(文本域)：\n");
      out.write("\t<textarea name=\"note\" cols=\"34\" rows=\"5\">\n");
      out.write("\t\n");
      out.write("\t</textarea>\n");
      out.write("\t<br>\n");
      out.write("\t<input type=\"hidden\" name=\"hiddenField\" value=\"hiddenvalue\"/>\n");
      out.write("\t<input type=\"submit\" value=\"提交(提交按钮)\">\n");
      out.write("\t<input type=\"reset\" value=\"重置(重置按钮)\">\n");
      out.write("\t\n");
      out.write("\t</form>\n");
      out.write("\t\n");
      out.write("</fieldset>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
